#!/usr/bin/env bash
set -euo pipefail

# Docker Traefik Worktree Router Manager
# Routes worktree docker-compose services via {worktree_name}.localhost

NETWORK_NAME="traefik-net"
TRAEFIK_CONTAINER="traefik-proxy"
TRAEFIK_PORT="${TRAEFIK_PORT:-80}"
DEFAULT_SERVICE_PORT="${TRAEFIK_DEFAULT_PORT:-80}"
WORKTREE_DIR=".worktrees"

# Find the git repo root
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

usage() {
    echo "Usage: $(basename "$0") <command> [args]"
    echo ""
    echo "Commands:"
    echo "  up                          Start shared Traefik reverse proxy"
    echo "  down                        Stop Traefik and remove shared network"
    echo "  start <worktree> [port]     Start worktree services with Traefik routing"
    echo "  stop <worktree>             Stop worktree services"
    echo "  list|ls                     List worktrees with docker-compose and their status"
    exit 1
}

ensure_network() {
    if ! docker network inspect "$NETWORK_NAME" &>/dev/null; then
        echo "Creating Docker network: $NETWORK_NAME"
        docker network create "$NETWORK_NAME"
    fi
}

cmd_up() {
    ensure_network

    if docker ps --format '{{.Names}}' | grep -q "^${TRAEFIK_CONTAINER}$"; then
        echo "Traefik is already running."
        echo "Dashboard: http://traefik.localhost:${TRAEFIK_PORT}"
        return 0
    fi

    # Remove stopped container if it exists
    docker rm -f "$TRAEFIK_CONTAINER" &>/dev/null || true

    echo "Starting Traefik on port ${TRAEFIK_PORT}..."
    docker run -d \
        --name "$TRAEFIK_CONTAINER" \
        --network "$NETWORK_NAME" \
        -p "${TRAEFIK_PORT}:80" \
        -p "8080:8080" \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        --label "traefik.enable=true" \
        --label "traefik.http.routers.dashboard.rule=Host(\`traefik.localhost\`)" \
        --label "traefik.http.routers.dashboard.service=api@internal" \
        traefik:v3.0 \
        --api.insecure=true \
        --providers.docker=true \
        --providers.docker.exposedbydefault=false \
        --providers.docker.network="$NETWORK_NAME" \
        --entrypoints.web.address=:80

    echo "Traefik started."
    echo "Dashboard: http://traefik.localhost:${TRAEFIK_PORT}"
}

cmd_down() {
    echo "Stopping Traefik..."
    docker rm -f "$TRAEFIK_CONTAINER" &>/dev/null || true

    if docker network inspect "$NETWORK_NAME" &>/dev/null; then
        # Only remove network if no other containers are using it
        local connected
        connected=$(docker network inspect "$NETWORK_NAME" --format '{{len .Containers}}')
        if [ "$connected" -eq 0 ]; then
            docker network rm "$NETWORK_NAME"
            echo "Removed network: $NETWORK_NAME"
        else
            echo "Network $NETWORK_NAME still has $connected connected containers. Not removing."
        fi
    fi

    echo "Traefik stopped."
}

cmd_start() {
    local worktree_name="${1:-}"
    local service_port="${2:-$DEFAULT_SERVICE_PORT}"

    if [ -z "$worktree_name" ]; then
        echo "Error: worktree name required"
        echo "Usage: $(basename "$0") start <worktree-name> [port]"
        exit 1
    fi

    local worktree_path="${REPO_ROOT}/${WORKTREE_DIR}/${worktree_name}"

    if [ ! -d "$worktree_path" ]; then
        echo "Error: Worktree not found at $worktree_path"
        exit 1
    fi

    if [ ! -f "$worktree_path/docker-compose.yml" ] && [ ! -f "$worktree_path/docker-compose.yaml" ] && [ ! -f "$worktree_path/compose.yml" ] && [ ! -f "$worktree_path/compose.yaml" ]; then
        echo "Error: No docker-compose file found in $worktree_path"
        exit 1
    fi

    # Find the compose file
    local compose_file
    for f in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
        if [ -f "$worktree_path/$f" ]; then
            compose_file="$f"
            break
        fi
    done

    # Ensure Traefik is running
    cmd_up

    # Determine which service to route to
    local target_service="${TRAEFIK_SERVICE:-}"
    if [ -z "$target_service" ]; then
        # Get the first service from the compose file
        target_service=$(docker compose -f "$worktree_path/$compose_file" config --services | head -1)
    fi

    # Generate traefik override compose file
    local override_file="$worktree_path/.docker-compose.traefik.yml"
    cat > "$override_file" <<YAML
# Auto-generated by traefik-manager.sh - do not edit
services:
  ${target_service}:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${worktree_name}.rule=Host(\`${worktree_name}.localhost\`)"
      - "traefik.http.routers.${worktree_name}.entrypoints=web"
      - "traefik.http.services.${worktree_name}.loadbalancer.server.port=${service_port}"
    networks:
      - traefik

networks:
  traefik:
    name: ${NETWORK_NAME}
    external: true
YAML

    echo "Starting services for worktree: $worktree_name"
    docker compose -f "$worktree_path/$compose_file" -f "$override_file" \
        -p "wt-${worktree_name}" up -d

    echo ""
    echo "Service is now accessible at: http://${worktree_name}.localhost"
    [ "$TRAEFIK_PORT" != "80" ] && echo "  (on port $TRAEFIK_PORT: http://${worktree_name}.localhost:${TRAEFIK_PORT})"
}

cmd_stop() {
    local worktree_name="${1:-}"

    if [ -z "$worktree_name" ]; then
        echo "Error: worktree name required"
        echo "Usage: $(basename "$0") stop <worktree-name>"
        exit 1
    fi

    local worktree_path="${REPO_ROOT}/${WORKTREE_DIR}/${worktree_name}"

    echo "Stopping services for worktree: $worktree_name"
    docker compose -p "wt-${worktree_name}" down 2>/dev/null || true

    # Clean up override file
    rm -f "$worktree_path/.docker-compose.traefik.yml" 2>/dev/null || true

    echo "Stopped: $worktree_name"
}

cmd_list() {
    echo "Worktrees with Docker Compose:"
    echo "================================"

    local found=0
    for dir in "$REPO_ROOT/$WORKTREE_DIR"/*/; do
        [ ! -d "$dir" ] && continue
        local name
        name=$(basename "$dir")

        local has_compose=false
        for f in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
            if [ -f "$dir/$f" ]; then
                has_compose=true
                break
            fi
        done

        if $has_compose; then
            found=1
            local status="stopped"
            if docker compose -p "wt-${name}" ps --status running 2>/dev/null | grep -q "running"; then
                status="running  -> http://${name}.localhost"
            fi
            echo "  $name: $status"
        fi
    done

    if [ "$found" -eq 0 ]; then
        echo "  (none found)"
    fi
}

# Main
command="${1:-}"
shift || true

case "$command" in
    up)       cmd_up ;;
    down)     cmd_down ;;
    start)    cmd_start "$@" ;;
    stop)     cmd_stop "$@" ;;
    list|ls)  cmd_list ;;
    *)        usage ;;
esac
